apiVersion: apps/v1
kind: Deployment
metadata:
  name: kurama-manager
  labels:
    app.kubernetes.io/name: kurama
    app.kubernetes.io/component: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kurama
      app.kubernetes.io/component: manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kurama
        app.kubernetes.io/component: manager
    spec:
      serviceAccountName: kurama-manager
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: manager
          image: 528081867341.dkr.ecr.eu-central-1.amazonaws.com/kurama@sha256:f6e144d606834e2ce06e5fc96b8b0f19d1bfe3a8ff5e582d710cae7b9e379f7a
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KURAMA_RUNNER_IMAGE
              value: 528081867341.dkr.ecr.eu-central-1.amazonaws.com/kurama@sha256:f6e144d606834e2ce06e5fc96b8b0f19d1bfe3a8ff5e582d710cae7b9e379f7a
            - name: KURAMA_RUNNER_IMAGE_PULL_SECRET
              value: ecr-pull-secret
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              memory: 64Mi
