apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shorturl-api-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: shorturl-api-auth
    creationPolicy: Owner
    template:
      metadata:
        labels: {}
        annotations: {}
  dataFrom:
    - extract:
        key: shorturl/api-auth
