{{- if .Values.secretsManagement.secretStore.create }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretsManagement.secretStore.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shorturl.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretsManagement.awsRegion | quote }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretsManagement.credentialsSecretName }}
            key: access-key-id
          secretAccessKeySecretRef:
            name: {{ .Values.secretsManagement.credentialsSecretName }}
            key: secret-access-key
{{- end }}
