apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shorturl.fullname" . }}-config
  labels:
    {{- include "shorturl.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- include "shorturl.configData" . | nindent 4 }}
