apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shorturl.fullname" . }}-config
  labels:
    {{- include "shorturl.labels" . | nindent 4 }}
data:
  config.yml: |
    postgresDB:
      host: {{ .Values.postgres.host }}
      user: {{ .Values.postgres.user }}
      password: {{ .Values.postgres.password }}
      dbName: {{ .Values.postgres.dbName }}
      port: "{{ .Values.postgres.port }}"
      sslmode: {{ .Values.postgres.sslMode }}
    server:
      restPort: "{{ .Values.server.restPort }}"
      dataCenterId: {{ .Values.server.dataCenterId }}
      mashineId: {{ .Values.server.machineId }}
