{{- if .Values.otel.sidecar.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-sidecar-config
  labels:
    {{- include "shorturl.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "shorturl.otelSidecarConfigData" . | nindent 4 }}
{{- end }}
