{{- if .Values.postgres.deployed }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-migrations
  labels:
    {{- include "shorturl.labels" . | nindent 4 }}
data:
  000001_init_schema.up.sql: |
    CREATE TABLE "shorten_url" (
      "id" bigint PRIMARY KEY,
      "short_url" varchar NOT NULL,
      "long_url" varchar NOT NULL
    );

    CREATE INDEX short_url_index
    ON shorten_url (short_url);

    CREATE INDEX long_url_index
    ON shorten_url (long_url);
  000001_init_schema.down.sql: |
    DROP TABLE IF EXISTS shorten_url;
  000002_add_unique_constraints.up.sql: |
    DROP INDEX IF EXISTS short_url_index;
    DROP INDEX IF EXISTS long_url_index;

    CREATE UNIQUE INDEX short_url_unique_index
    ON shorten_url (short_url);

    CREATE UNIQUE INDEX long_url_unique_index
    ON shorten_url (long_url);
  000002_add_unique_constraints.down.sql: |
    DROP INDEX IF EXISTS short_url_unique_index;
    DROP INDEX IF EXISTS long_url_unique_index;

    CREATE INDEX short_url_index
    ON shorten_url (short_url);

    CREATE INDEX long_url_index
    ON shorten_url (long_url);
{{- end }}
