{{- if .Values.postgres.deployed }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  labels:
    {{- include "shorturl.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: postgres-credentials
    creationPolicy: Orphan
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: {{ .Values.secretsManagement.postgresSecretName | quote }}
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.secretsManagement.postgresSecretName | quote }}
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: {{ .Values.secretsManagement.postgresSecretName | quote }}
        property: dbname
{{- end }}
