{{- if .Values.postgres.deployed }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.host }}
  labels:
    {{- include "shorturl.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: shorturl
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
{{- end }}
