{{- if or (not .Values.ci.enabled) .Values.ci.controllersEnabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amenotejikara
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: {{ .Values.git.repoURL | quote }}
    targetRevision: {{ .Values.git.targetRevision | quote }}
    path: k8s/amenotejikara
  destination:
    server: https://kubernetes.default.svc
    namespace: shorturl
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
