git:
  repoURL: "https://github.com/mykyta-kravchenko98/shorturl-gitops.git"
  targetRevision: "main"

shorturl:
  valuesFile: values-local.yaml

kurama:
  externalSecret:
    enabled: true

ci:
  enabled: false
  controllersEnabled: false
